version: "3.7"
services:
  app:
    build:
      args:
        user: nacho
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: enviame
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - challenge

networks:
  challenge:
    driver: bridge
